/**
 * HeyGen Interactive Avatar / Video Generation service.
 *
 * Generates cinematic product-origin videos using HeyGen's API.
 * Each video features a narrating avatar telling the blockchain-verified
 * provenance story of an authenticated product.
 */
import 'server-only'

const HEYGEN_API = 'https://api.heygen.com'

function apiKey() {
  const key = process.env.HEYGEN_API_KEY
  if (!key) throw new Error('HEYGEN_API_KEY is not configured')
  return key
}

function headers() {
  return {
    'Content-Type': 'application/json',
    'X-Api-Key': apiKey(),
  }
}

// ── Types ────────────────────────────────────────────────────────────────────

export interface StoryVideoRequest {
  /** The narration script (generated by GPT-4) */
  script: string
  /** Product name — used in the video title overlay */
  productName: string
  /** Brand name */
  brand: string
  /** Avatar ID from HeyGen (defaults to a professional narrator) */
  avatarId?: string
  /** Voice ID — defaults to a cinematic male narrator */
  voiceId?: string
  /** Background style */
  background?: string
}

export interface StoryVideoResult {
  videoId: string
  status: 'pending' | 'processing' | 'completed' | 'failed'
  videoUrl?: string
  thumbnailUrl?: string
  duration?: number
}

// ── Avatar listing ───────────────────────────────────────────────────────────

export async function listAvatars() {
  const res = await fetch(`${HEYGEN_API}/v2/avatars`, { headers: headers() })
  if (!res.ok) throw new Error(`HeyGen avatars: ${res.status}`)
  const data = await res.json()
  return data.data?.avatars ?? []
}

// ── Video generation ─────────────────────────────────────────────────────────

/**
 * Create a cinematic product-origin video via HeyGen.
 */
export async function createStoryVideo(req: StoryVideoRequest): Promise<StoryVideoResult> {
  const avatarId = req.avatarId || 'Daisy-inskirt-20220818'
  const voiceId = req.voiceId || 'en-US-ChristopherNeural'

  const payload = {
    video_inputs: [
      {
        character: {
          type: 'avatar',
          avatar_id: avatarId,
          avatar_style: 'normal',
        },
        voice: {
          type: 'text',
          input_text: req.script,
          voice_id: voiceId,
          speed: 0.95,
        },
        background: {
          type: 'color',
          value: '#0a0a0a',
        },
      },
    ],
    dimension: { width: 1920, height: 1080 },
    aspect_ratio: '16:9',
    test: false,
  }

  const res = await fetch(`${HEYGEN_API}/v2/video/generate`, {
    method: 'POST',
    headers: headers(),
    body: JSON.stringify(payload),
  })

  if (!res.ok) {
    const err = await res.text()
    throw new Error(`HeyGen video create failed (${res.status}): ${err}`)
  }

  const data = await res.json()
  const videoId = data.data?.video_id

  if (!videoId) throw new Error('HeyGen did not return a video_id')

  return { videoId, status: 'pending' }
}

/**
 * Poll HeyGen for video status / completion.
 */
export async function getVideoStatus(videoId: string): Promise<StoryVideoResult> {
  const res = await fetch(`${HEYGEN_API}/v1/video_status.get?video_id=${videoId}`, {
    headers: headers(),
  })

  if (!res.ok) throw new Error(`HeyGen status check failed: ${res.status}`)

  const data = await res.json()
  const info = data.data

  return {
    videoId,
    status: info.status === 'completed' ? 'completed'
      : info.status === 'failed' ? 'failed'
      : 'processing',
    videoUrl: info.video_url ?? undefined,
    thumbnailUrl: info.thumbnail_url ?? undefined,
    duration: info.duration ?? undefined,
  }
}
